# needed for HTML test...
config :html_test, 
  :required => [:req_target_2],
  :layout   => 'lib/layout_template.rhtml',
  :debug_required => [:debug],
  :test_required  => [:qunit]
  
config :req_target_2,
  :required => [:req_target_1],
  :dynamic_required => [:dynamic_req_target_1]

config :test_test,
  :test_layout   => 'lib/test_layout.rhtml',
  :debug_required => [:debug],
  :test_required  => [:qunit],
  :theme => nil

## module related tests

config :package_test,
  :required => [:req_target_1],
  :dynamic_required => [:req_target_2],
  :use_modules => true
  
config :module_test,
  :required => [:req_target_1],
  :use_modules => true
  
config :no_modules_test,
  :required => [:req_target_1],
  :use_modules => true # uses modules here but all files disable it
  
config :no_loader_test,
  :required => [:req_target_1],
  :use_loader => false
  
config :no_loader_items_test,
  :required => [],
  :use_loader => true, # by default
  :use_modules => true # must enable to support loading modules
  
# has no JS in it
config :no_javascript,
  :use_loader => true,
  :use_modules => false
  
  